# Author settings
author:
  name: "Chengjie Ren"
  avatar: "/images/ren-profile.jpg"  # 确保图片存在于 images/ 文件夹中
  bio: "Professor of Soil Microbial Ecology at Northwest A&F University"
  location: "Ankang, Shaanxi Province, China"
  email: "rencj1991@nwsuaf.edu.cn"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=FjwhLQsAAAAJ"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-XXXX-XXXX"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Ren-chengjie"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Chengjie-Ren"
    - label: "Official Profile"
      icon: "fas fa-university"
      url: "https://nxy.nwafu.edu.cn/szdw/zjrc/cef9a16ea1404c7799678d14f1166663.htm"
